name: Build

on:
  push:
    # branches: [ "main" ]
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ["crux", "equuleus"]

    steps:

      - name: Pull Docker Container
        run: docker pull vyos/vyos-build:${{ matrix.version }} 

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Checkout VyOS Repo
        uses: actions/checkout@v3
        with:
          repository: vyos/vyos-build
          ref: ${{ matrix.version }}
          path: vyos-build

      # - name: Checkout VyOS build branch
      #   run: git clone -b ${{ matrix.version }} --single-branch https://github.com/vyos/vyos-build

      - name: Run Build ISO
        run: docker run --rm -i --privileged -v $(pwd):/vyos -w /vyos vyos/vyos-build:${{ matrix.version }} bash ./build.sh

      - name: Check Build output
        run: |
          ls -la vyos-build/build

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.version }}-iso
          path: vyos-build/build/*.iso

        