name: Build

on:
  push:
    # branches: [ "main" ]
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - uses: actions/checkout@v3
      #   with:
      #     repository: 'https://github.com/vyos/vyos-build'
      #     ref: 'crux'

      - name: Checkout VyOS build branch
        run: git clone -b crux --single-branch https://github.com/vyos/vyos-build

      - name: Run Build ISO
        run: docker run --rm -i --privileged -v $(pwd):/vyos -w /vyos vyos/vyos-build:crux ./build.sh


        